CREATE TABLE AUX_AFASTAMENTO
(
  AUXAF_CODIGO 		INTEGER IDENTITY(1,1)	  NOT NULL,
  AUXEM_EMPS_CODIGO	VARCHAR(5)  NULL,
  AUXFU_MATRICULA	VARCHAR(30) NULL,
  AUXAF_COD_AFASTAMENTO	VARCHAR(5)  NULL,
  AUXAF_TIPO_AFASTAMENTO VARCHAR(1)     NULL,
  AUXAF_INICIO 		DATETIME    NULL,
  AUXAF_TERMINO 		DATETIME    NULL ,
  AUXAF_OPERACAO 	VARCHAR(1)  NULL  ,
  AUXLG_MOMENTO 		DATETIME    NULL,
  AUXLG_CHAVE_LOG 	VARCHAR(55) NULL ,
  CONSTRAINT PK_AUX_AFASTAMENTO PRIMARY KEY( AUXAF_CODIGO )
)
CREATE INDEX ID_AUXLG_CHAVE_LOG_AF ON AUX_AFASTAMENTO (AUXLG_CHAVE_LOG)
GRANT SELECT,INSERT,UPDATE,DELETE ON AUX_AFASTAMENTO TO RL_USUARIO_AUXILIAR
GO
 

